### ISSUE TITLE
Nuget package availability

### ISSUE THREAD

**Issue by AymericGrassart** [microsoft/Tools-for-Health-Data-Anonymization#229]
As a repo for health data anonymization tools, is it possible to get nuget packages of the Core and Shared projects published so they can be used within an existing dotnet application (not through CLI)?

Thank you,
Aymeric Grassart

**Comment by alexathomases** [comment]
Hi Aymeric, thanks for your inquiry. The packages are already available through [Azure Artifacts](https://microsofthealthoss.visualstudio.com/FhirServer/_artifacts/feed/Public) rather than nuget. For instance, the Dicom.Anonymizer.Core project can be found [here](https://microsofthealthoss.visualstudio.com/FhirServer/_artifacts/feed/Public/NuGet/Microsoft.Health.Dicom.Anonymizer.Core/overview/3.1.0.90).

Please see this [related issue](https://github.com/microsoft/dicom-server/discussions/1544#discussioncomment-2648858) for further details.
